### ISSUE TITLE
Credits for the project

### ISSUE THREAD

**Issue by shivasiddharth** [AdvaitT17/Personal-Assistant-based-on-AI#4]
Hello,
I have spent so much of my time innovating and improving the google assistant project. if you wish to copy any part of the project you need to credit me for that. You have mentioned as though you used only my installer. Even the Readme that you are using was drafted by me. I guess you need to credit me for the entire project and not just the installer.
Regards

**Comment by AdvaitT17** [comment]
I saw that installer script and the files only few are edited otherwise they are completely made by google

**Comment by shivasiddharth** [comment]
Forget it ! Its not a big deal to me. But learn to credit other's work instead of just copying.

**Comment by shivasiddharth** [comment]
Lol, i have never seen such a guy like you...  I will give you a better idea for getting rid of my credits issues posts. Delete the git and fork it again..

**Comment by shivasiddharth** [comment]
Hello,
No use deleting my comments. All those GPIO triggering and controlling was my idea. This is not  a big issue for me but you must learn to credit other's work.

**Comment by AdvaitT17** [comment]
I will definitely add your credit..after my project works

**Comment by shivasiddharth** [comment]
You need to clearly state that the project was cloned/forked or modified not just the installer.
